import type { HubPost, FindTeamPost, OutsourceJob } from "@/types";

// ===== HUB POSTS =====
export const mockHubPosts: HubPost[] = [
  {
    id: "post-1",
    type: "recruit",
    title: "รับลูกทีมด่วน! ทำงาน Facebook/IG",
    author: {
      name: "JohnBoost Team",
      avatar: "J",
      rating: 4.9,
      verified: true,
      type: "seller",
      memberCount: 45,
      totalPaid: 125000,
    },
    description:
      "รับลูกทีมเพิ่ม 10 คน งานเยอะมาก จ่ายไวทุก 2 วัน มีงานให้ทำตลอด รับทั้งมือใหม่และมือเก่า สอนงานให้!",
    platforms: ["facebook", "instagram"],
    payRate: { min: 0.3, max: 1.5, unit: "บาท/งาน" },
    requirements: ["มีโทรศัพท์", "ออนไลน์ได้ทุกวัน", "จองงานได้วันละ 50+"],
    benefits: ["จ่ายไวทุก 2 วัน", "โบนัสท้ายเดือน", "สอนงานฟรี", "กลุ่ม Line สำหรับสมาชิก"],
    memberCount: 45,
    openSlots: 10,
    applicants: 18,
    views: 234,
    interested: 18,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    isHot: true,
  },
  {
    id: "post-2",
    type: "find-team",
    title: "หาทีมค่ะ ทำงานมา 6 เดือน Rating 4.8",
    author: {
      name: "น้องมิ้นท์",
      avatar: "ม",
      rating: 4.8,
      verified: false,
      type: "worker",
    },
    description:
      "เคยทำงานกับทีมมาก่อน 6 เดือน งาน Facebook/IG/TikTok ได้หมด ทำงานได้วันละ 100+ งาน ต้องการทีมที่จ่ายตรงเวลา",
    platforms: ["facebook", "instagram", "tiktok"],
    experience: "6 เดือน",
    completedJobs: 1250,
    expectedPay: "0.5+ บาท/งาน",
    availability: "ทุกวัน 09:00-22:00",
    views: 156,
    interested: 8,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "post-3",
    type: "outsource",
    title: "โยนงาน IG Follow 500 คน ด่วน!",
    author: {
      name: "SocialPro",
      avatar: "S",
      rating: 4.7,
      verified: true,
      type: "seller",
    },
    description:
      "มีงาน Follow IG 500 คน ต้องการภายในวันนี้ งานเกินรับไม่ไหว ราคาคุยได้",
    platforms: ["instagram"],
    jobType: "follow",
    quantity: 500,
    budget: "200 บาท",
    deadline: "วันนี้ 20:00",
    views: 89,
    interested: 5,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    isUrgent: true,
  },
  {
    id: "post-4",
    type: "recruit",
    title: "รับสมาชิกทีมใหม่ งาน TikTok View/Like",
    author: {
      name: "TikTok Master",
      avatar: "T",
      rating: 4.6,
      verified: true,
      type: "seller",
      memberCount: 32,
      totalPaid: 85000,
    },
    description:
      "ทีมเปิดใหม่ รับคนเข้าทีม 20 คน เน้นงาน TikTok โดยเฉพาะ ค่าตอบแทนดี มีโบนัส Top Worker ทุกเดือน",
    platforms: ["tiktok"],
    payRate: { min: 0.1, max: 0.5, unit: "บาท/งาน" },
    requirements: ["มี TikTok", "ทำงานได้ทุกวัน", "จองงานได้ 100+/วัน"],
    benefits: ["โบนัส Top Worker", "งานเยอะ", "จ่ายทุก 3 วัน"],
    openSlots: 20,
    applicants: 22,
    views: 178,
    interested: 22,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "post-5",
    type: "find-team",
    title: "มือใหม่หาทีม อยากเรียนรู้งาน",
    author: {
      name: "เบส",
      avatar: "เ",
      rating: 0,
      verified: false,
      type: "worker",
    },
    description:
      "เพิ่งเริ่มต้น อยากหาทีมที่สอนงานให้ ทำงานได้ทั้งวัน มีโทรศัพท์ 2 เครื่อง",
    platforms: ["facebook", "instagram", "tiktok"],
    experience: "มือใหม่",
    availability: "Full-time",
    views: 67,
    interested: 3,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "post-6",
    type: "outsource",
    title: "รับโยนงาน Comment FB ภาษาไทย",
    author: {
      name: "ร้านค้าออนไลน์",
      avatar: "ร",
      rating: 4.5,
      verified: false,
      type: "seller",
    },
    description:
      "มีงาน Comment Facebook ภาษาไทย 100 comment ต้องการทีมที่มี Worker คุณภาพ",
    platforms: ["facebook"],
    jobType: "comment",
    quantity: 100,
    budget: "300 บาท",
    deadline: "พรุ่งนี้ 18:00",
    views: 45,
    interested: 4,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: "recruit-3",
    type: "recruit",
    title: "หาทีมงานคอมเม้น Facebook ภาษาไทย",
    author: {
      name: "Comment Pro",
      avatar: "C",
      rating: 4.8,
      verified: true,
      type: "seller",
      memberCount: 28,
      totalPaid: 95000,
    },
    description:
      "รับคนพิมพ์เร็ว ทำงานคอมเม้น Facebook เนื้อหาภาษาไทย ต้องพิมพ์ถูกต้อง ไม่ผิดสเปล ค่าตอบแทนดี",
    platforms: ["facebook"],
    payRate: { min: 1.0, max: 2.0, unit: "บาท/เม้น" },
    requirements: ["พิมพ์ภาษาไทยถูกต้อง", "ทำงานรวดเร็ว", "มีความรับผิดชอบ"],
    benefits: ["ค่าตอบแทนสูง", "จ่ายทันที", "งานประจำ"],
    openSlots: 15,
    applicants: 12,
    views: 156,
    interested: 12,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "recruit-4",
    type: "recruit",
    title: "รับน้องใหม่! สอนงานตั้งแต่เริ่มต้น",
    author: {
      name: "Beginner Friendly Team",
      avatar: "B",
      rating: 4.7,
      verified: false,
      type: "seller",
      memberCount: 15,
      totalPaid: 45000,
    },
    description:
      "ทีมสำหรับมือใหม่โดยเฉพาะ สอนงานตั้งแต่พื้นฐาน มีพี่เลี้ยงดูแล ค่อยๆ เรียนรู้ไปด้วยกัน",
    platforms: ["facebook", "instagram", "tiktok"],
    payRate: { min: 0.2, max: 0.8, unit: "บาท/งาน" },
    requirements: ["มีใจอยากเรียนรู้", "มีเวลาอย่างน้อย 2-3 ชม./วัน"],
    benefits: ["สอนงานฟรี", "มีพี่เลี้ยง", "เริ่มจากงานง่ายๆ"],
    openSlots: 10,
    applicants: 8,
    views: 89,
    interested: 8,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
];

// ===== HUB STATS =====
export const mockHubStats = [
  { label: "โพสต์หาลูกทีม", value: 156 },
  { label: "โพสต์หาทีม", value: 89 },
  { label: "งานรอโยน", value: 34 },
  { label: "จับคู่สำเร็จ", value: 1250 },
];

// ===== FIND TEAM POSTS =====
export const mockFindTeamPosts: FindTeamPost[] = [
  {
    id: "find-1",
    title: "หาทีมค่ะ ทำงานมา 6 เดือน Rating 4.8",
    author: {
      name: "น้องมิ้นท์",
      avatar: "ม",
      rating: 4.8,
      level: "Gold",
    },
    description:
      "เคยทำงานกับทีมมาก่อน 6 เดือน งาน Facebook/IG/TikTok ได้หมด ทำงานได้วันละ 100+ งาน ต้องการทีมที่จ่ายตรงเวลา",
    platforms: ["facebook", "instagram", "tiktok"],
    experience: "6 เดือน",
    completedJobs: 1250,
    completionRate: 98.5,
    expectedPay: "0.5+ บาท/งาน",
    availability: "ทุกวัน 09:00-22:00",
    skills: ["ไลค์", "เม้น", "Follow", "View"],
    portfolio: "ทำงานกับ 3 ทีมมาก่อน ผลงานดี",
    views: 156,
    interested: 8,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    isTopWorker: true,
  },
  {
    id: "find-2",
    title: "Worker มือเก๋า ประสบการณ์ 1 ปี+",
    author: {
      name: "พี่ต้น",
      avatar: "ต",
      rating: 4.9,
      level: "Platinum",
    },
    description:
      "ทำงานมา 1 ปีกว่า เน้นงานคุณภาพ ไม่เคยถูก Reject งาน หาทีมที่มีงานสม่ำเสมอและจ่ายตรงเวลา",
    platforms: ["facebook", "instagram"],
    experience: "1 ปี 3 เดือน",
    completedJobs: 3500,
    completionRate: 99.2,
    expectedPay: "0.8+ บาท/งาน",
    availability: "จันทร์-เสาร์ 10:00-20:00",
    skills: ["ไลค์", "เม้นคุณภาพ", "Follow"],
    portfolio: "เคยเป็น Top Worker ประจำเดือน 5 ครั้ง",
    views: 234,
    interested: 15,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    isTopWorker: true,
  },
  {
    id: "find-3",
    title: "มือใหม่หาทีม อยากเรียนรู้งาน",
    author: {
      name: "น้องเบส",
      avatar: "เ",
      rating: 0,
      level: "New",
    },
    description:
      "เพิ่งเริ่มต้น อยากหาทีมที่สอนงานให้ ทำงานได้ทั้งวัน มีโทรศัพท์ 2 เครื่อง พร้อมเรียนรู้ทุกอย่าง",
    platforms: ["facebook", "instagram", "tiktok"],
    experience: "มือใหม่",
    completedJobs: 0,
    completionRate: 0,
    expectedPay: "ตามที่ทีมกำหนด",
    availability: "Full-time ทุกวัน",
    skills: ["พร้อมเรียนรู้"],
    portfolio: "มีโทรศัพท์ 2 เครื่อง พร้อมทำงาน",
    views: 67,
    interested: 3,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "find-4",
    title: "หาทีมงาน TikTok โดยเฉพาะ",
    author: {
      name: "แนน",
      avatar: "แ",
      rating: 4.6,
      level: "Silver",
    },
    description:
      "ถนัดงาน TikTok โดยเฉพาะ View/Like/Follow ทำได้เร็วมาก หาทีมที่เน้นงาน TikTok",
    platforms: ["tiktok"],
    experience: "4 เดือน",
    completedJobs: 850,
    completionRate: 97.5,
    expectedPay: "0.3+ บาท/งาน",
    availability: "ทุกวัน หลัง 17:00",
    skills: ["TikTok View", "TikTok Like", "TikTok Follow"],
    portfolio: "ทำงาน TikTok ได้วันละ 500+",
    views: 98,
    interested: 6,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: "find-5",
    title: "ทำงานพาร์ทไทม์ หาทีมที่ยืดหยุ่น",
    author: {
      name: "อุ้ม",
      avatar: "อ",
      rating: 4.5,
      level: "Bronze",
    },
    description:
      "เป็นนักศึกษา ทำงานพาร์ทไทม์ได้วันละ 3-4 ชม. หาทีมที่เข้าใจและยืดหยุ่นเรื่องเวลา",
    platforms: ["facebook", "instagram"],
    experience: "2 เดือน",
    completedJobs: 320,
    completionRate: 95.0,
    expectedPay: "0.4+ บาท/งาน",
    availability: "จันทร์-ศุกร์ 18:00-22:00, เสาร์-อาทิตย์ เต็มวัน",
    skills: ["ไลค์", "Follow"],
    portfolio: "ทำงานสม่ำเสมอ แม้จะพาร์ทไทม์",
    views: 45,
    interested: 2,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// ===== OUTSOURCE JOBS =====
export const mockOutsourceJobs: OutsourceJob[] = [
  {
    id: "out-1",
    title: "โยนงาน IG Follow 500 คน ด่วน!",
    author: {
      name: "SocialPro",
      avatar: "S",
      rating: 4.7,
      verified: true,
      totalOutsourced: 25,
    },
    description:
      "มีงาน Follow IG 500 คน ต้องการภายในวันนี้ งานเกินรับไม่ไหว ราคาคุยได้ ต้องการทีมที่มี Worker พร้อมทำทันที",
    platform: "instagram",
    jobType: "follow",
    quantity: 500,
    budget: 200,
    pricePerUnit: 0.4,
    deadline: new Date(Date.now() + 3600000 * 4).toISOString(),
    targetUrl: "https://instagram.com/shop_abc",
    requirements: ["ส่งงานภายในวันนี้", "แอคคุณภาพ", "รายงานความคืบหน้า"],
    views: 89,
    bids: 5,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    isUrgent: true,
  },
  {
    id: "out-2",
    title: "รับโยนงาน Comment FB ภาษาไทย 100 เม้น",
    author: {
      name: "ร้านค้าออนไลน์",
      avatar: "ร",
      rating: 4.5,
      verified: false,
      totalOutsourced: 8,
    },
    description:
      "มีงาน Comment Facebook ภาษาไทย 100 comment ต้องการทีมที่มี Worker คุณภาพ เม้นต้องหลากหลาย ไม่ซ้ำกัน",
    platform: "facebook",
    jobType: "comment",
    quantity: 100,
    budget: 300,
    pricePerUnit: 3.0,
    deadline: new Date(Date.now() + 3600000 * 24).toISOString(),
    targetUrl: "https://facebook.com/post/xxx",
    requirements: ["เม้นภาษาไทย", "ไม่ซ้ำกัน", "แอคคนไทยจริง"],
    views: 45,
    bids: 4,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: "out-3",
    title: "โยนงาน TikTok View 10,000 View",
    author: {
      name: "TikTok Shop",
      avatar: "T",
      rating: 4.8,
      verified: true,
      totalOutsourced: 42,
    },
    description:
      "ต้องการ View TikTok 10,000 View สำหรับวิดีโอสินค้าใหม่ ส่งงานภายใน 2 วัน ราคาคุยได้",
    platform: "tiktok",
    jobType: "view",
    quantity: 10000,
    budget: 500,
    pricePerUnit: 0.05,
    deadline: new Date(Date.now() + 3600000 * 48).toISOString(),
    targetUrl: "https://tiktok.com/@shop/video/xxx",
    requirements: ["View จริง", "ไม่หลุด", "รายงานทุก 2 ชม."],
    views: 156,
    bids: 8,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "out-4",
    title: "ด่วน! Like Facebook 2,000 Like",
    author: {
      name: "Marketing Pro",
      avatar: "M",
      rating: 4.6,
      verified: true,
      totalOutsourced: 18,
    },
    description:
      "ต้องการ Like Facebook 2,000 Like ด่วนภายใน 6 ชม. มีงานต่อเนื่องให้ทีมที่ทำได้ดี",
    platform: "facebook",
    jobType: "like",
    quantity: 2000,
    budget: 400,
    pricePerUnit: 0.2,
    deadline: new Date(Date.now() + 3600000 * 6).toISOString(),
    targetUrl: "https://facebook.com/page/post/yyy",
    requirements: ["ส่งงานใน 6 ชม.", "Like คุณภาพ"],
    views: 78,
    bids: 6,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    isUrgent: true,
  },
  {
    id: "out-5",
    title: "โยนงาน Share Facebook 300 Share",
    author: {
      name: "Event Organizer",
      avatar: "E",
      rating: 4.4,
      verified: false,
      totalOutsourced: 5,
    },
    description:
      "ต้องการ Share โพสต์ Facebook 300 Share สำหรับโปรโมทอีเว้นท์ ส่งงานภายใน 3 วัน",
    platform: "facebook",
    jobType: "share",
    quantity: 300,
    budget: 450,
    pricePerUnit: 1.5,
    deadline: new Date(Date.now() + 3600000 * 72).toISOString(),
    targetUrl: "https://facebook.com/events/xxx",
    requirements: ["Share เป็น Public", "แอคไทยแท้"],
    views: 34,
    bids: 2,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// ===== HELPER FUNCTIONS =====
export const getHubPostsByType = (type: "all" | "recruit" | "find-team" | "outsource") => {
  if (type === "all") return mockHubPosts;
  return mockHubPosts.filter((post) => post.type === type);
};

export const getRecruitPosts = () => getHubPostsByType("recruit");
export const getFindTeamPosts = () => getHubPostsByType("find-team");
export const getOutsourcePosts = () => getHubPostsByType("outsource");
