import type {
  Seller,
  Worker,
  Team,
  TeamMember,
  StoreService,
  Order,
  OrderItem,
  Job,
  JobClaim,
  WorkerAccount,
} from "@/types";

// ===== MOCK SELLER =====
export const mockSeller: Seller = {
  id: "seller-1",
  userId: "user-1",
  displayName: "John",
  storeName: "JohnBoost",
  storeSlug: "johnboost",
  avatar: "/avatars/seller-1.jpg",
  bio: "บริการปั้มยอด Social Media คุณภาพ ส่งไว จ่ายปลอดภัย",
  lineId: "@johnboost",
  phone: "080-123-4567",
  email: "john@example.com",
  plan: "pro",
  planExpiresAt: "2025-12-31",
  balance: 2450,
  totalOrders: 2450,
  totalRevenue: 285000,
  rating: 4.9,
  ratingCount: 156,
  storeTheme: "meelike",
  isActive: true,
  isVerified: true,
  createdAt: "2024-01-01",
  updatedAt: new Date().toISOString(),
};

// ===== MOCK WORKERS =====
export const mockWorkers: Worker[] = [
  {
    id: "worker-1",
    userId: "user-w1",
    displayName: "นุ่น",
    avatar: "/avatars/worker-1.jpg",
    bio: "ขยันทำงานค่ะ",
    lineId: "@nuna",
    phone: "081-111-1111",
    bankName: "กสิกร",
    bankAccount: "123-4-56789-0",
    bankAccountName: "นางสาว นุ่น ใจดี",
    promptPayId: "0811111111",
    totalJobs: 256,
    totalEarned: 12500,
    completionRate: 98.5,
    rating: 4.9,
    ratingCount: 245,
    level: "gold",
    totalJobsCompleted: 245,
    pendingBalance: 15,
    availableBalance: 127.5,
    isActive: true,
    isBanned: false,
    teamIds: ["team-1", "team-2"],
    createdAt: "2024-01-15",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "worker-2",
    userId: "user-w2",
    displayName: "มิ้นท์",
    avatar: "/avatars/worker-2.jpg",
    bio: "รับงานทุกประเภท",
    lineId: "@mint",
    phone: "082-222-2222",
    bankName: "กรุงไทย",
    bankAccount: "987-6-54321-0",
    bankAccountName: "นางสาว มิ้นท์ สดใส",
    promptPayId: "0822222222",
    totalJobs: 134,
    totalEarned: 6800,
    completionRate: 96.2,
    rating: 4.7,
    ratingCount: 128,
    level: "silver",
    totalJobsCompleted: 128,
    pendingBalance: 25,
    availableBalance: 85.5,
    isActive: true,
    isBanned: false,
    teamIds: ["team-1"],
    createdAt: "2024-02-20",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "worker-3",
    userId: "user-w3",
    displayName: "เบส",
    avatar: "/avatars/worker-3.jpg",
    lineId: "@bass",
    phone: "083-333-3333",
    totalJobs: 52,
    totalEarned: 2100,
    completionRate: 92.5,
    rating: 4.5,
    ratingCount: 45,
    level: "bronze",
    totalJobsCompleted: 45,
    pendingBalance: 0,
    availableBalance: 42,
    isActive: false,
    isBanned: false,
    teamIds: ["team-1"],
    createdAt: "2024-06-10",
    lastActiveAt: "2024-12-20",
  },
];

// ===== MOCK TEAM =====
export const mockTeam: Team = {
  id: "team-1",
  sellerId: "seller-1",
  name: "JohnBoost Team",
  description: "ทีมงานคุณภาพ รับงาน Social Media ทุกประเภท",
  rules: [
    "แคปหลักฐานทุกงาน",
    "ส่งงานตรงเวลา",
    "ไม่รับงานถ้าทำไม่ไหว",
    "สอบถามก่อนได้เสมอ",
  ],
  inviteCode: "JOHN-2024-ABC",
  requireApproval: true,
  isPublic: true,
  isRecruiting: true,
  recruitingMessage: "รับน้องใหม่ทุกวัน! จ่ายไวทุก 2 วัน",
  memberCount: 45,
  activeJobCount: 3,
  totalJobsCompleted: 1250,
  isActive: true,
  createdAt: "2024-01-01",
  updatedAt: new Date().toISOString(),
};

// ===== MOCK TEAM MEMBERS =====
export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    teamId: "team-1",
    workerId: "worker-1",
    status: "active",
    role: "member",
    jobsCompleted: 180,
    totalEarned: 9500,
    rating: 4.9,
    ratingCount: 175,
    joinedAt: "2024-01-20",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "tm-2",
    teamId: "team-1",
    workerId: "worker-2",
    status: "active",
    role: "member",
    jobsCompleted: 95,
    totalEarned: 4800,
    rating: 4.7,
    ratingCount: 92,
    joinedAt: "2024-03-01",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "tm-3",
    teamId: "team-1",
    workerId: "worker-3",
    status: "inactive",
    role: "member",
    jobsCompleted: 35,
    totalEarned: 1400,
    rating: 4.5,
    ratingCount: 33,
    joinedAt: "2024-06-15",
    lastActiveAt: "2024-12-20",
  },
];

// ===== MOCK SERVICES =====
export const mockServices: StoreService[] = [
  {
    id: "svc-1",
    sellerId: "seller-1",
    name: "ไลค์ Facebook (Bot)",
    description: "ไลค์โพสต์ Facebook ด้วยบอทคุณภาพ ส่งไวใน 1 ชั่วโมง",
    category: "facebook",
    type: "like",
    serviceType: "bot",
    costPrice: 0.08,
    sellPrice: 0.15,
    minQuantity: 100,
    maxQuantity: 10000,
    meelikeServiceId: "ml-fb-like",
    estimatedTime: "1 ชม.",
    isActive: true,
    orderCount: 520,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-2",
    sellerId: "seller-1",
    name: "ไลค์ Facebook (คนไทยจริง)",
    description: "ไลค์จากคนไทยจริง แอคคุณภาพ 100%",
    category: "facebook",
    type: "like",
    serviceType: "human",
    costPrice: 0.2,
    sellPrice: 0.5,
    minQuantity: 50,
    maxQuantity: 2000,
    estimatedTime: "1-6 ชม.",
    isActive: true,
    orderCount: 180,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-3",
    sellerId: "seller-1",
    name: "เม้น Facebook (คนไทยจริง)",
    description: "เม้นภาษาไทย เหมือนคนจริง 100%",
    category: "facebook",
    type: "comment",
    serviceType: "human",
    costPrice: 0.5,
    sellPrice: 1.5,
    minQuantity: 10,
    maxQuantity: 500,
    estimatedTime: "2-12 ชม.",
    isActive: true,
    orderCount: 85,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-4",
    sellerId: "seller-1",
    name: "Follow Instagram (Bot)",
    description: "เพิ่มผู้ติดตาม IG ด้วยบอทคุณภาพ",
    category: "instagram",
    type: "follow",
    serviceType: "bot",
    costPrice: 0.1,
    sellPrice: 0.2,
    minQuantity: 100,
    maxQuantity: 5000,
    meelikeServiceId: "ml-ig-follow",
    estimatedTime: "1-2 ชม.",
    isActive: true,
    orderCount: 320,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-5",
    sellerId: "seller-1",
    name: "Follow Instagram (คนไทยจริง)",
    description: "ผู้ติดตามคนไทยจริง แอคคุณภาพ",
    category: "instagram",
    type: "follow",
    serviceType: "human",
    costPrice: 0.3,
    sellPrice: 0.8,
    minQuantity: 50,
    maxQuantity: 1000,
    estimatedTime: "2-8 ชม.",
    isActive: true,
    orderCount: 95,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-6",
    sellerId: "seller-1",
    name: "View TikTok (Bot)",
    description: "เพิ่มยอดวิว TikTok ส่งไวมาก",
    category: "tiktok",
    type: "view",
    serviceType: "bot",
    costPrice: 0.03,
    sellPrice: 0.08,
    minQuantity: 500,
    maxQuantity: 100000,
    meelikeServiceId: "ml-tt-view",
    estimatedTime: "30 นาที",
    isActive: true,
    orderCount: 450,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
];

// ===== MOCK ORDERS =====
export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "ORD-2024-001",
    sellerId: "seller-1",
    customer: {
      name: "คุณสมชาย",
      contactType: "line",
      contactValue: "@somchai_shop",
      note: "ต้องการด่วนครับ รบกวนเร่งให้หน่อย",
    },
    items: [
      {
        id: "item-1",
        orderId: "order-1",
        serviceId: "svc-1",
        serviceName: "ไลค์ Facebook (Bot)",
        serviceType: "bot",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/post/xxx",
        quantity: 1000,
        unitPrice: 0.15,
        subtotal: 150,
        costPerUnit: 0.08,
        totalCost: 80,
        profit: 70,
        profitPercent: 87.5,
        status: "completed",
        progress: 100,
        completedQuantity: 1000,
        meelikeOrderId: "ML-12345",
        startedAt: "2024-12-30T07:32:00Z",
        completedAt: "2024-12-30T07:45:00Z",
      },
      {
        id: "item-2",
        orderId: "order-1",
        serviceId: "svc-3",
        serviceName: "เม้น Facebook (คนไทยจริง)",
        serviceType: "human",
        platform: "facebook",
        type: "comment",
        targetUrl: "https://facebook.com/post/xxx",
        quantity: 50,
        commentTemplates: [
          "สินค้าดีมากครับ",
          "แนะนำเลยค่ะ",
          "ชอบมากๆ",
        ],
        unitPrice: 1.5,
        subtotal: 75,
        costPerUnit: 0.5,
        totalCost: 25,
        profit: 50,
        profitPercent: 200,
        status: "processing",
        progress: 64,
        completedQuantity: 32,
        jobId: "job-1",
        startedAt: "2024-12-30T07:50:00Z",
      },
      {
        id: "item-3",
        orderId: "order-1",
        serviceId: "svc-5",
        serviceName: "Follow Instagram (คนไทยจริง)",
        serviceType: "human",
        platform: "instagram",
        type: "follow",
        targetUrl: "https://instagram.com/somchai_shop",
        quantity: 200,
        unitPrice: 0.8,
        subtotal: 160,
        costPerUnit: 0.3,
        totalCost: 60,
        profit: 100,
        profitPercent: 166.67,
        status: "pending",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 385,
    discount: 0,
    total: 385,
    totalCost: 165,
    totalProfit: 220,
    paymentStatus: "paid",
    paymentProof: "/proofs/slip-001.jpg",
    paidAt: "2024-12-30T07:31:00Z",
    status: "processing",
    progress: 65,
    trackingUrl: "seller.meelike.com/track/ORD-2024-001",
    createdAt: "2024-12-30T07:30:00Z",
    updatedAt: new Date().toISOString(),
    confirmedAt: "2024-12-30T07:31:00Z",
  },
  {
    id: "order-2",
    orderNumber: "ORD-2024-002",
    sellerId: "seller-1",
    customer: {
      name: "ร้านขายของออนไลน์",
      contactType: "facebook",
      contactValue: "fb.com/shop",
    },
    items: [
      {
        id: "item-4",
        orderId: "order-2",
        serviceId: "svc-6",
        serviceName: "View TikTok (Bot)",
        serviceType: "bot",
        platform: "tiktok",
        type: "view",
        targetUrl: "https://tiktok.com/@shop/video/xxx",
        quantity: 5000,
        unitPrice: 0.08,
        subtotal: 400,
        costPerUnit: 0.03,
        totalCost: 150,
        profit: 250,
        profitPercent: 166.67,
        status: "completed",
        progress: 100,
        completedQuantity: 5000,
        meelikeOrderId: "ML-12346",
        startedAt: "2024-12-29T03:15:00Z",
        completedAt: "2024-12-29T03:45:00Z",
      },
    ],
    subtotal: 400,
    discount: 0,
    total: 400,
    totalCost: 150,
    totalProfit: 250,
    paymentStatus: "paid",
    paidAt: "2024-12-29T03:10:00Z",
    status: "completed",
    progress: 100,
    trackingUrl: "seller.meelike.com/track/ORD-2024-002",
    createdAt: "2024-12-29T03:00:00Z",
    updatedAt: "2024-12-29T03:45:00Z",
    confirmedAt: "2024-12-29T03:10:00Z",
    completedAt: "2024-12-29T03:45:00Z",
  },
];

// ===== MOCK JOBS =====
export const mockJobs: Job[] = [
  {
    id: "job-1",
    sellerId: "seller-1",
    orderId: "order-1",
    title: "500 ไลค์ FB",
    type: "like",
    platform: "facebook",
    targetUrl: "https://facebook.com/page/xxx",
    targetQuantity: 500,
    pricePerUnit: 0.2,
    requirements: "แอคจริงหน้าคน ไม่เอาโปรไฟล์การ์ตูน\nแคปหลักฐานทุกงาน",
    endsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    teamId: "team-1",
    visibility: "all_members",
    status: "in_progress",
    claimedQuantity: 420,
    completedQuantity: 380,
    createdAt: "2024-12-30T07:50:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "job-2",
    sellerId: "seller-1",
    title: "100 เม้น FB",
    type: "comment",
    platform: "facebook",
    targetUrl: "https://facebook.com/post/yyy",
    targetQuantity: 100,
    pricePerUnit: 0.5,
    commentTemplates: [
      "สินค้าดีมากครับ",
      "แนะนำเลยค่ะ",
      "ชอบมากๆ",
      "ราคาโอเคเลย",
    ],
    requirements: "เม้นให้เป็นธรรมชาติ ไม่ซ้ำกัน",
    endsAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    teamId: "team-1",
    visibility: "all_members",
    status: "open",
    claimedQuantity: 45,
    completedQuantity: 32,
    createdAt: "2024-12-30T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
];

// ===== MOCK JOB CLAIMS =====
export const mockJobClaims: JobClaim[] = [
  {
    id: "claim-1",
    jobId: "job-1",
    workerId: "worker-1",
    workerAccountId: "wa-1",
    quantity: 30,
    earnAmount: 6,
    status: "submitted",
    submittedAt: new Date().toISOString(),
    proofUrls: ["/proofs/claim-1-1.jpg", "/proofs/claim-1-2.jpg"],
    actualQuantity: 30,
    createdAt: "2024-12-30T08:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "claim-2",
    jobId: "job-1",
    workerId: "worker-2",
    workerAccountId: "wa-2",
    quantity: 50,
    earnAmount: 10,
    status: "submitted",
    submittedAt: new Date().toISOString(),
    proofUrls: ["/proofs/claim-2-1.jpg", "/proofs/claim-2-2.jpg", "/proofs/claim-2-3.jpg"],
    actualQuantity: 50,
    createdAt: "2024-12-30T08:15:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "claim-3",
    jobId: "job-1",
    workerId: "worker-1",
    workerAccountId: "wa-1",
    quantity: 20,
    earnAmount: 4,
    status: "approved",
    submittedAt: "2024-12-30T09:00:00Z",
    proofUrls: ["/proofs/claim-3-1.jpg"],
    actualQuantity: 20,
    reviewedAt: "2024-12-30T09:30:00Z",
    reviewedBy: "seller-1",
    sellerRating: 5,
    createdAt: "2024-12-30T08:30:00Z",
    updatedAt: "2024-12-30T09:30:00Z",
  },
];

// ===== MOCK WORKER ACCOUNTS =====
export const mockWorkerAccounts: WorkerAccount[] = [
  {
    id: "wa-1",
    workerId: "worker-1",
    platform: "facebook",
    username: "nuna.jaidee",
    profileUrl: "https://facebook.com/nuna.jaidee",
    screenshotUrl: "/screenshots/wa-1.jpg",
    verificationStatus: "verified",
    verifiedAt: "2024-01-20",
    verifiedBy: "ai",
    aiResult: {
      passed: true,
      confidence: 0.95,
      hasProfilePicture: true,
      detectedFollowers: 850,
      usernameMatch: true,
      notes: "Account verified successfully",
    },
    followers: 850,
    profilePictureExists: true,
    accountAge: "3 years",
    isActive: true,
    lastUsedAt: new Date().toISOString(),
    jobsCompleted: 180,
    createdAt: "2024-01-20",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wa-2",
    workerId: "worker-2",
    platform: "facebook",
    username: "mint.sodsai",
    profileUrl: "https://facebook.com/mint.sodsai",
    screenshotUrl: "/screenshots/wa-2.jpg",
    verificationStatus: "verified",
    verifiedAt: "2024-03-05",
    verifiedBy: "ai",
    aiResult: {
      passed: true,
      confidence: 0.92,
      hasProfilePicture: true,
      detectedFollowers: 620,
      usernameMatch: true,
      notes: "Account verified successfully",
    },
    followers: 620,
    profilePictureExists: true,
    accountAge: "2 years",
    isActive: true,
    lastUsedAt: new Date().toISOString(),
    jobsCompleted: 95,
    createdAt: "2024-03-05",
    updatedAt: new Date().toISOString(),
  },
];

// ===== STATS =====
export const mockSellerStats = {
  todayRevenue: 1250,
  monthRevenue: 28500,
  todayOrders: 12,
  monthOrders: 245,
  activeTeamMembers: 38,
  pendingReviews: 5,
  pendingPayouts: 2450,
};

export const mockWorkerStats = {
  availableBalance: 127.5,
  pendingBalance: 15,
  totalEarned: 2450,
  todayEarned: 24,
  weeklyRank: 1,
  streak: 7,
};


