import type { Job } from "@/types";

// ===== MOCK JOBS =====
export const mockJobs: Job[] = [
  {
    id: "job-1",
    sellerId: "seller-1",
    orderId: "order-1",
    title: "500 ไลค์ FB",
    type: "like",
    platform: "facebook",
    targetUrl: "https://facebook.com/page/xxx",
    targetQuantity: 500,
    pricePerUnit: 0.2,
    requirements: "แอคจริงหน้าคน ไม่เอาโปรไฟล์การ์ตูน\nแคปหลักฐานทุกงาน",
    endsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    teamId: "team-1",
    visibility: "all_members",
    status: "in_progress",
    claimedQuantity: 420,
    completedQuantity: 380,
    createdAt: "2024-12-30T07:50:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "job-2",
    sellerId: "seller-1",
    title: "100 เม้น FB",
    type: "comment",
    platform: "facebook",
    targetUrl: "https://facebook.com/post/yyy",
    targetQuantity: 100,
    pricePerUnit: 0.5,
    commentTemplates: [
      "สินค้าดีมากครับ",
      "แนะนำเลยค่ะ",
      "ชอบมากๆ",
      "ราคาโอเคเลย",
    ],
    requirements: "เม้นให้เป็นธรรมชาติ ไม่ซ้ำกัน",
    endsAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    teamId: "team-1",
    visibility: "all_members",
    status: "open",
    claimedQuantity: 45,
    completedQuantity: 32,
    createdAt: "2024-12-30T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
];
