import type { MeeLikeService } from "@/types";

// Mock data สำหรับบริการจาก MeeLike API
// ในการใช้งานจริงจะดึงจาก https://api.meelike-th.com/api/v2
export const mockMeeLikeServices: MeeLikeService[] = [
  // ===== FACEBOOK =====
  {
    service: "1",
    name: "🔵 Facebook Page Likes [Thai]",
    type: "Page Likes",
    category: "Facebook",
    rate: "80",
    min: "100",
    max: "50000",
    refill: true,
    cancel: false,
    description: "ไลค์เพจ Facebook จากบัญชีคนไทยจริง คุณภาพสูง ไม่หลุด",
    averageTime: "24-48 ชั่วโมง",
  },
  {
    service: "2",
    name: "🔵 Facebook Post Likes [Fast]",
    type: "Post Likes",
    category: "Facebook",
    rate: "15",
    min: "100",
    max: "100000",
    refill: false,
    cancel: true,
    description: "ไลค์โพสต์ Facebook ส่งไว ราคาถูก",
    averageTime: "1-6 ชั่วโมง",
  },
  {
    service: "3",
    name: "🔵 Facebook Post Likes [Thai Real]",
    type: "Post Likes",
    category: "Facebook",
    rate: "50",
    min: "50",
    max: "10000",
    refill: true,
    cancel: false,
    description: "ไลค์โพสต์จากบัญชีคนไทยจริง มีโปรไฟล์ครบ",
    averageTime: "12-24 ชั่วโมง",
  },
  {
    service: "4",
    name: "🔵 Facebook Comments [Custom]",
    type: "Comments",
    category: "Facebook",
    rate: "200",
    min: "10",
    max: "1000",
    refill: false,
    cancel: false,
    description: "คอมเมนต์ Facebook ข้อความกำหนดเอง",
    averageTime: "6-12 ชั่วโมง",
  },
  {
    service: "5",
    name: "🔵 Facebook Followers [Profile]",
    type: "Followers",
    category: "Facebook",
    rate: "100",
    min: "100",
    max: "50000",
    refill: true,
    cancel: false,
    description: "เพิ่มผู้ติดตามโปรไฟล์ Facebook",
    averageTime: "24-72 ชั่วโมง",
  },
  {
    service: "6",
    name: "🔵 Facebook Video Views",
    type: "Views",
    category: "Facebook",
    rate: "8",
    min: "1000",
    max: "10000000",
    refill: false,
    cancel: true,
    description: "วิวคลิป Facebook ส่งไว",
    averageTime: "0-1 ชั่วโมง",
  },
  {
    service: "7",
    name: "🔵 Facebook Share [Post]",
    type: "Shares",
    category: "Facebook",
    rate: "120",
    min: "50",
    max: "5000",
    refill: false,
    cancel: false,
    description: "แชร์โพสต์ Facebook",
    averageTime: "6-24 ชั่วโมง",
  },

  // ===== INSTAGRAM =====
  {
    service: "101",
    name: "📸 Instagram Followers [Fast]",
    type: "Followers",
    category: "Instagram",
    rate: "25",
    min: "100",
    max: "100000",
    refill: false,
    cancel: true,
    description: "เพิ่มผู้ติดตาม Instagram ส่งไว",
    averageTime: "0-6 ชั่วโมง",
  },
  {
    service: "102",
    name: "📸 Instagram Followers [Thai Real]",
    type: "Followers",
    category: "Instagram",
    rate: "150",
    min: "50",
    max: "10000",
    refill: true,
    cancel: false,
    description: "ผู้ติดตามคนไทยจริง มีรูปโปรไฟล์ โพสต์ครบ",
    averageTime: "24-72 ชั่วโมง",
  },
  {
    service: "103",
    name: "📸 Instagram Likes [Fast]",
    type: "Likes",
    category: "Instagram",
    rate: "10",
    min: "100",
    max: "50000",
    refill: false,
    cancel: true,
    description: "ไลค์รูป Instagram ส่งไว ราคาถูก",
    averageTime: "0-2 ชั่วโมง",
  },
  {
    service: "104",
    name: "📸 Instagram Likes [Thai Real]",
    type: "Likes",
    category: "Instagram",
    rate: "60",
    min: "50",
    max: "10000",
    refill: false,
    cancel: false,
    description: "ไลค์จากบัญชีคนไทยจริง",
    averageTime: "6-24 ชั่วโมง",
  },
  {
    service: "105",
    name: "📸 Instagram Comments [Custom]",
    type: "Comments",
    category: "Instagram",
    rate: "250",
    min: "10",
    max: "500",
    refill: false,
    cancel: false,
    description: "คอมเมนต์ Instagram ข้อความกำหนดเอง",
    averageTime: "6-12 ชั่วโมง",
  },
  {
    service: "106",
    name: "📸 Instagram Views [Reels]",
    type: "Views",
    category: "Instagram",
    rate: "5",
    min: "1000",
    max: "10000000",
    refill: false,
    cancel: true,
    description: "วิว Reels Instagram",
    averageTime: "0-1 ชั่วโมง",
  },
  {
    service: "107",
    name: "📸 Instagram Story Views",
    type: "Views",
    category: "Instagram",
    rate: "8",
    min: "100",
    max: "100000",
    refill: false,
    cancel: true,
    description: "วิว Story Instagram",
    averageTime: "0-1 ชั่วโมง",
  },

  // ===== TIKTOK =====
  {
    service: "201",
    name: "🎵 TikTok Followers [Fast]",
    type: "Followers",
    category: "TikTok",
    rate: "30",
    min: "100",
    max: "100000",
    refill: false,
    cancel: true,
    description: "เพิ่มผู้ติดตาม TikTok ส่งไว",
    averageTime: "0-6 ชั่วโมง",
  },
  {
    service: "202",
    name: "🎵 TikTok Followers [Thai Real]",
    type: "Followers",
    category: "TikTok",
    rate: "180",
    min: "50",
    max: "10000",
    refill: true,
    cancel: false,
    description: "ผู้ติดตาม TikTok คนไทยจริง",
    averageTime: "24-72 ชั่วโมง",
  },
  {
    service: "203",
    name: "🎵 TikTok Likes [Fast]",
    type: "Likes",
    category: "TikTok",
    rate: "8",
    min: "100",
    max: "100000",
    refill: false,
    cancel: true,
    description: "ไลค์คลิป TikTok ส่งไว ราคาถูก",
    averageTime: "0-2 ชั่วโมง",
  },
  {
    service: "204",
    name: "🎵 TikTok Views [Fast]",
    type: "Views",
    category: "TikTok",
    rate: "3",
    min: "1000",
    max: "10000000",
    refill: false,
    cancel: true,
    description: "วิวคลิป TikTok ส่งไวมาก",
    averageTime: "0-30 นาที",
  },
  {
    service: "205",
    name: "🎵 TikTok Comments [Custom]",
    type: "Comments",
    category: "TikTok",
    rate: "300",
    min: "10",
    max: "500",
    refill: false,
    cancel: false,
    description: "คอมเมนต์ TikTok ข้อความกำหนดเอง",
    averageTime: "6-24 ชั่วโมง",
  },
  {
    service: "206",
    name: "🎵 TikTok Shares",
    type: "Shares",
    category: "TikTok",
    rate: "50",
    min: "100",
    max: "10000",
    refill: false,
    cancel: true,
    description: "แชร์คลิป TikTok",
    averageTime: "1-6 ชั่วโมง",
  },
  {
    service: "207",
    name: "🎵 TikTok Saves",
    type: "Saves",
    category: "TikTok",
    rate: "40",
    min: "100",
    max: "50000",
    refill: false,
    cancel: true,
    description: "Save คลิป TikTok",
    averageTime: "1-6 ชั่วโมง",
  },

  // ===== YOUTUBE =====
  {
    service: "301",
    name: "▶️ YouTube Subscribers [Fast]",
    type: "Subscribers",
    category: "YouTube",
    rate: "200",
    min: "100",
    max: "10000",
    refill: false,
    cancel: false,
    description: "เพิ่ม Subscribers YouTube",
    averageTime: "24-72 ชั่วโมง",
  },
  {
    service: "302",
    name: "▶️ YouTube Views [Fast]",
    type: "Views",
    category: "YouTube",
    rate: "20",
    min: "1000",
    max: "1000000",
    refill: false,
    cancel: true,
    description: "วิว YouTube ส่งไว",
    averageTime: "0-6 ชั่วโมง",
  },
  {
    service: "303",
    name: "▶️ YouTube Views [High Retention]",
    type: "Views",
    category: "YouTube",
    rate: "80",
    min: "1000",
    max: "100000",
    refill: false,
    cancel: false,
    description: "วิว YouTube Retention สูง 70%+",
    averageTime: "24-48 ชั่วโมง",
  },
  {
    service: "304",
    name: "▶️ YouTube Likes",
    type: "Likes",
    category: "YouTube",
    rate: "50",
    min: "50",
    max: "50000",
    refill: false,
    cancel: true,
    description: "ไลค์คลิป YouTube",
    averageTime: "1-12 ชั่วโมง",
  },
  {
    service: "305",
    name: "▶️ YouTube Comments [Custom]",
    type: "Comments",
    category: "YouTube",
    rate: "500",
    min: "10",
    max: "500",
    refill: false,
    cancel: false,
    description: "คอมเมนต์ YouTube ข้อความกำหนดเอง",
    averageTime: "12-24 ชั่วโมง",
  },
  {
    service: "306",
    name: "▶️ YouTube Shorts Views",
    type: "Views",
    category: "YouTube",
    rate: "10",
    min: "1000",
    max: "10000000",
    refill: false,
    cancel: true,
    description: "วิว YouTube Shorts",
    averageTime: "0-2 ชั่วโมง",
  },

  // ===== TWITTER/X =====
  {
    service: "401",
    name: "🐦 Twitter/X Followers",
    type: "Followers",
    category: "Twitter",
    rate: "100",
    min: "100",
    max: "50000",
    refill: false,
    cancel: true,
    description: "เพิ่มผู้ติดตาม Twitter/X",
    averageTime: "1-24 ชั่วโมง",
  },
  {
    service: "402",
    name: "🐦 Twitter/X Likes",
    type: "Likes",
    category: "Twitter",
    rate: "30",
    min: "50",
    max: "50000",
    refill: false,
    cancel: true,
    description: "ไลค์ทวีต Twitter/X",
    averageTime: "0-6 ชั่วโมง",
  },
  {
    service: "403",
    name: "🐦 Twitter/X Retweets",
    type: "Retweets",
    category: "Twitter",
    rate: "50",
    min: "50",
    max: "10000",
    refill: false,
    cancel: true,
    description: "Retweet ทวีต",
    averageTime: "0-6 ชั่วโมง",
  },
  {
    service: "404",
    name: "🐦 Twitter/X Views",
    type: "Views",
    category: "Twitter",
    rate: "5",
    min: "1000",
    max: "10000000",
    refill: false,
    cancel: true,
    description: "วิวทวีต Twitter/X",
    averageTime: "0-1 ชั่วโมง",
  },
];

// Helper functions
export function getMeeLikeServicesByCategory(category: string): MeeLikeService[] {
  return mockMeeLikeServices.filter(s => s.category.toLowerCase() === category.toLowerCase());
}

export function searchMeeLikeServices(query: string): MeeLikeService[] {
  const q = query.toLowerCase();
  return mockMeeLikeServices.filter(s => 
    s.name.toLowerCase().includes(q) || 
    s.type.toLowerCase().includes(q) ||
    s.category.toLowerCase().includes(q)
  );
}

// Convert rate per 1000 to rate per unit
export function getMeeLikeRatePerUnit(rate: string): number {
  return parseFloat(rate) / 1000;
}

// Categories available
export const meeLikeCategories = [
  { value: "all", label: "ทั้งหมด" },
  { value: "Facebook", label: "🔵 Facebook" },
  { value: "Instagram", label: "📸 Instagram" },
  { value: "TikTok", label: "🎵 TikTok" },
  { value: "YouTube", label: "▶️ YouTube" },
  { value: "Twitter", label: "🐦 Twitter/X" },
];
