import type {
  Seller,
  StoreService,
  Order,
} from "@/types";

// ===== MOCK SELLER =====
export const mockSeller: Seller = {
  id: "seller-1",
  userId: "user-1",
  displayName: "John",
  storeName: "JohnBoost",
  storeSlug: "johnboost",
  avatar: "/avatars/seller-1.jpg",
  bio: "บริการปั้มยอด Social Media คุณภาพ ส่งไว จ่ายปลอดภัย",
  lineId: "@johnboost",
  phone: "080-123-4567",
  email: "john@example.com",
  plan: "pro",
  planExpiresAt: "2025-12-31",
  balance: 2450,
  totalOrders: 2450,
  totalRevenue: 285000,
  rating: 4.9,
  ratingCount: 156,
  storeTheme: "meelike",
  isActive: true,
  isVerified: true,
  createdAt: "2024-01-01",
  updatedAt: new Date().toISOString(),
};

// ===== MOCK SERVICES =====
export const mockServices: StoreService[] = [
  {
    id: "svc-1",
    sellerId: "seller-1",
    name: "ไลค์ Facebook (Bot)",
    description: "ไลค์โพสต์ Facebook ด้วยบอทคุณภาพ ส่งไวใน 1 ชั่วโมง",
    category: "facebook",
    type: "like",
    serviceType: "bot",
    costPrice: 0.08,
    sellPrice: 0.15,
    minQuantity: 100,
    maxQuantity: 10000,
    meelikeServiceId: "ml-fb-like",
    estimatedTime: "1 ชม.",
    isActive: true,
    orderCount: 520,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-2",
    sellerId: "seller-1",
    name: "ไลค์ Facebook (คนไทยจริง)",
    description: "ไลค์จากคนไทยจริง แอคคุณภาพ 100%",
    category: "facebook",
    type: "like",
    serviceType: "human",
    costPrice: 0.2,
    sellPrice: 0.5,
    minQuantity: 50,
    maxQuantity: 2000,
    estimatedTime: "1-6 ชม.",
    isActive: true,
    orderCount: 180,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-3",
    sellerId: "seller-1",
    name: "เม้น Facebook (คนไทยจริง)",
    description: "เม้นภาษาไทย เหมือนคนจริง 100%",
    category: "facebook",
    type: "comment",
    serviceType: "human",
    costPrice: 0.5,
    sellPrice: 1.5,
    minQuantity: 10,
    maxQuantity: 500,
    estimatedTime: "2-12 ชม.",
    isActive: true,
    orderCount: 85,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-4",
    sellerId: "seller-1",
    name: "Follow Instagram (Bot)",
    description: "เพิ่มผู้ติดตาม IG ด้วยบอทคุณภาพ",
    category: "instagram",
    type: "follow",
    serviceType: "bot",
    costPrice: 0.1,
    sellPrice: 0.2,
    minQuantity: 100,
    maxQuantity: 5000,
    meelikeServiceId: "ml-ig-follow",
    estimatedTime: "1-2 ชม.",
    isActive: true,
    orderCount: 320,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-5",
    sellerId: "seller-1",
    name: "Follow Instagram (คนไทยจริง)",
    description: "ผู้ติดตามคนไทยจริง แอคคุณภาพ",
    category: "instagram",
    type: "follow",
    serviceType: "human",
    costPrice: 0.3,
    sellPrice: 0.8,
    minQuantity: 50,
    maxQuantity: 1000,
    estimatedTime: "2-8 ชม.",
    isActive: true,
    orderCount: 95,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc-6",
    sellerId: "seller-1",
    name: "View TikTok (Bot)",
    description: "เพิ่มยอดวิว TikTok ส่งไวมาก",
    category: "tiktok",
    type: "view",
    serviceType: "bot",
    costPrice: 0.03,
    sellPrice: 0.08,
    minQuantity: 500,
    maxQuantity: 100000,
    meelikeServiceId: "ml-tt-view",
    estimatedTime: "30 นาที",
    isActive: true,
    orderCount: 450,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
];

// ===== MOCK ORDERS =====
export const mockOrders: Order[] = [
  // ===== PENDING (รอชำระเงิน) =====
  {
    id: "order-pending-1",
    orderNumber: "ORD-2025-007",
    sellerId: "seller-1",
    customer: {
      name: "คุณนิด้า",
      contactType: "line",
      contactValue: "@nida_beauty",
      note: "รบกวนส่งสลิปแล้วค่ะ รอยืนยันนะคะ",
    },
    items: [
      {
        id: "item-pending-1",
        orderId: "order-pending-1",
        serviceId: "svc-2",
        serviceName: "ไลค์ Facebook (คนไทยจริง)",
        serviceType: "human",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/nida.beauty/posts/123",
        quantity: 500,
        unitPrice: 0.5,
        subtotal: 250,
        costPerUnit: 0.2,
        totalCost: 100,
        profit: 150,
        profitPercent: 150,
        status: "pending",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 250,
    discount: 0,
    total: 250,
    totalCost: 100,
    totalProfit: 150,
    paymentStatus: "pending",
    status: "pending",
    progress: 0,
    trackingUrl: "seller.meelike.com/track/ORD-2025-007",
    createdAt: "2025-01-01T09:30:00Z",
    updatedAt: "2025-01-01T09:30:00Z",
  },
  {
    id: "order-pending-2",
    orderNumber: "ORD-2025-006",
    sellerId: "seller-1",
    customer: {
      name: "ร้านกาแฟ",
      contactType: "phone",
      contactValue: "081-234-5678",
    },
    items: [
      {
        id: "item-pending-2a",
        orderId: "order-pending-2",
        serviceId: "svc-4",
        serviceName: "Follow Instagram (Bot)",
        serviceType: "bot",
        platform: "instagram",
        type: "follow",
        targetUrl: "https://instagram.com/coffee_thai",
        quantity: 1000,
        unitPrice: 0.2,
        subtotal: 200,
        costPerUnit: 0.1,
        totalCost: 100,
        profit: 100,
        profitPercent: 100,
        status: "pending",
        progress: 0,
        completedQuantity: 0,
      },
      {
        id: "item-pending-2b",
        orderId: "order-pending-2",
        serviceId: "svc-6",
        serviceName: "View TikTok (Bot)",
        serviceType: "bot",
        platform: "tiktok",
        type: "view",
        targetUrl: "https://tiktok.com/@coffee_thai/video/456",
        quantity: 10000,
        unitPrice: 0.08,
        subtotal: 800,
        costPerUnit: 0.03,
        totalCost: 300,
        profit: 500,
        profitPercent: 166.67,
        status: "pending",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 1000,
    discount: 50,
    total: 950,
    totalCost: 400,
    totalProfit: 550,
    paymentStatus: "pending",
    status: "pending",
    progress: 0,
    trackingUrl: "seller.meelike.com/track/ORD-2025-006",
    createdAt: "2025-01-01T08:15:00Z",
    updatedAt: "2025-01-01T08:15:00Z",
  },

  // ===== PROCESSING (กำลังดำเนินการ) =====
  {
    id: "order-1",
    orderNumber: "ORD-2025-005",
    sellerId: "seller-1",
    customer: {
      name: "คุณสมชาย",
      contactType: "line",
      contactValue: "@somchai_shop",
      note: "ต้องการด่วนครับ รบกวนเร่งให้หน่อย",
    },
    items: [
      {
        id: "item-1",
        orderId: "order-1",
        serviceId: "svc-1",
        serviceName: "ไลค์ Facebook (Bot)",
        serviceType: "bot",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/somchai/posts/999",
        quantity: 1000,
        unitPrice: 0.15,
        subtotal: 150,
        costPerUnit: 0.08,
        totalCost: 80,
        profit: 70,
        profitPercent: 87.5,
        status: "completed",
        progress: 100,
        completedQuantity: 1000,
        meelikeOrderId: "ML-12345",
        startedAt: "2024-12-30T07:32:00Z",
        completedAt: "2024-12-30T07:45:00Z",
      },
      {
        id: "item-2",
        orderId: "order-1",
        serviceId: "svc-3",
        serviceName: "เม้น Facebook (คนไทยจริง)",
        serviceType: "human",
        platform: "facebook",
        type: "comment",
        targetUrl: "https://facebook.com/somchai/posts/999",
        quantity: 50,
        commentTemplates: [
          "สินค้าดีมากครับ",
          "แนะนำเลยค่ะ",
          "ชอบมากๆ",
        ],
        unitPrice: 1.5,
        subtotal: 75,
        costPerUnit: 0.5,
        totalCost: 25,
        profit: 50,
        profitPercent: 200,
        status: "processing",
        progress: 64,
        completedQuantity: 32,
        jobId: "job-1",
        startedAt: "2024-12-30T07:50:00Z",
      },
      {
        id: "item-3",
        orderId: "order-1",
        serviceId: "svc-5",
        serviceName: "Follow Instagram (คนไทยจริง)",
        serviceType: "human",
        platform: "instagram",
        type: "follow",
        targetUrl: "https://instagram.com/somchai_shop",
        quantity: 200,
        unitPrice: 0.8,
        subtotal: 160,
        costPerUnit: 0.3,
        totalCost: 60,
        profit: 100,
        profitPercent: 166.67,
        status: "pending",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 385,
    discount: 0,
    total: 385,
    totalCost: 165,
    totalProfit: 220,
    paymentStatus: "paid",
    paymentProof: "/proofs/slip-001.jpg",
    paidAt: "2024-12-30T07:31:00Z",
    status: "processing",
    progress: 65,
    trackingUrl: "seller.meelike.com/track/ORD-2025-005",
    createdAt: "2024-12-30T07:30:00Z",
    updatedAt: new Date().toISOString(),
    confirmedAt: "2024-12-30T07:31:00Z",
  },
  {
    id: "order-processing-2",
    orderNumber: "ORD-2025-004",
    sellerId: "seller-1",
    customer: {
      name: "Beauty Shop",
      contactType: "line",
      contactValue: "@beautyshop_th",
    },
    items: [
      {
        id: "item-proc-2",
        orderId: "order-processing-2",
        serviceId: "svc-6",
        serviceName: "View TikTok (Bot)",
        serviceType: "bot",
        platform: "tiktok",
        type: "view",
        targetUrl: "https://tiktok.com/@beautyshop/video/789",
        quantity: 50000,
        unitPrice: 0.08,
        subtotal: 4000,
        costPerUnit: 0.03,
        totalCost: 1500,
        profit: 2500,
        profitPercent: 166.67,
        status: "processing",
        progress: 45,
        completedQuantity: 22500,
        meelikeOrderId: "ML-12350",
        startedAt: "2024-12-31T14:00:00Z",
      },
    ],
    subtotal: 4000,
    discount: 200,
    total: 3800,
    totalCost: 1500,
    totalProfit: 2300,
    paymentStatus: "paid",
    paymentProof: "/proofs/slip-004.jpg",
    paidAt: "2024-12-31T13:55:00Z",
    status: "processing",
    progress: 45,
    trackingUrl: "seller.meelike.com/track/ORD-2025-004",
    createdAt: "2024-12-31T13:50:00Z",
    updatedAt: new Date().toISOString(),
    confirmedAt: "2024-12-31T13:55:00Z",
  },

  // ===== COMPLETED (เสร็จสิ้น) =====
  {
    id: "order-2",
    orderNumber: "ORD-2025-003",
    sellerId: "seller-1",
    customer: {
      name: "ร้านขายของออนไลน์",
      contactType: "facebook",
      contactValue: "fb.com/onlineshop",
    },
    items: [
      {
        id: "item-4",
        orderId: "order-2",
        serviceId: "svc-6",
        serviceName: "View TikTok (Bot)",
        serviceType: "bot",
        platform: "tiktok",
        type: "view",
        targetUrl: "https://tiktok.com/@onlineshop/video/xxx",
        quantity: 5000,
        unitPrice: 0.08,
        subtotal: 400,
        costPerUnit: 0.03,
        totalCost: 150,
        profit: 250,
        profitPercent: 166.67,
        status: "completed",
        progress: 100,
        completedQuantity: 5000,
        meelikeOrderId: "ML-12346",
        startedAt: "2024-12-29T03:15:00Z",
        completedAt: "2024-12-29T03:45:00Z",
      },
    ],
    subtotal: 400,
    discount: 0,
    total: 400,
    totalCost: 150,
    totalProfit: 250,
    paymentStatus: "paid",
    paidAt: "2024-12-29T03:10:00Z",
    status: "completed",
    progress: 100,
    trackingUrl: "seller.meelike.com/track/ORD-2025-003",
    createdAt: "2024-12-29T03:00:00Z",
    updatedAt: "2024-12-29T03:45:00Z",
    confirmedAt: "2024-12-29T03:10:00Z",
    completedAt: "2024-12-29T03:45:00Z",
  },
  {
    id: "order-completed-2",
    orderNumber: "ORD-2025-002",
    sellerId: "seller-1",
    customer: {
      name: "คุณมายด์",
      contactType: "line",
      contactValue: "@mind_makeup",
    },
    items: [
      {
        id: "item-comp-2a",
        orderId: "order-completed-2",
        serviceId: "svc-1",
        serviceName: "ไลค์ Facebook (Bot)",
        serviceType: "bot",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/mindmakeup/posts/111",
        quantity: 2000,
        unitPrice: 0.15,
        subtotal: 300,
        costPerUnit: 0.08,
        totalCost: 160,
        profit: 140,
        profitPercent: 87.5,
        status: "completed",
        progress: 100,
        completedQuantity: 2000,
        meelikeOrderId: "ML-12340",
        startedAt: "2024-12-28T10:00:00Z",
        completedAt: "2024-12-28T10:30:00Z",
      },
      {
        id: "item-comp-2b",
        orderId: "order-completed-2",
        serviceId: "svc-2",
        serviceName: "ไลค์ Facebook (คนไทยจริง)",
        serviceType: "human",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/mindmakeup/posts/111",
        quantity: 300,
        unitPrice: 0.5,
        subtotal: 150,
        costPerUnit: 0.2,
        totalCost: 60,
        profit: 90,
        profitPercent: 150,
        status: "completed",
        progress: 100,
        completedQuantity: 300,
        jobId: "job-10",
        startedAt: "2024-12-28T11:00:00Z",
        completedAt: "2024-12-28T14:30:00Z",
      },
    ],
    subtotal: 450,
    discount: 0,
    total: 450,
    totalCost: 220,
    totalProfit: 230,
    paymentStatus: "paid",
    paymentProof: "/proofs/slip-002.jpg",
    paidAt: "2024-12-28T09:50:00Z",
    status: "completed",
    progress: 100,
    trackingUrl: "seller.meelike.com/track/ORD-2025-002",
    createdAt: "2024-12-28T09:45:00Z",
    updatedAt: "2024-12-28T14:30:00Z",
    confirmedAt: "2024-12-28T09:50:00Z",
    completedAt: "2024-12-28T14:30:00Z",
  },
  {
    id: "order-completed-3",
    orderNumber: "ORD-2025-001",
    sellerId: "seller-1",
    customer: {
      name: "Fitness Club",
      contactType: "email",
      contactValue: "info@fitnessclub.com",
    },
    items: [
      {
        id: "item-comp-3",
        orderId: "order-completed-3",
        serviceId: "svc-5",
        serviceName: "Follow Instagram (คนไทยจริง)",
        serviceType: "human",
        platform: "instagram",
        type: "follow",
        targetUrl: "https://instagram.com/fitnessclub_th",
        quantity: 500,
        unitPrice: 0.8,
        subtotal: 400,
        costPerUnit: 0.3,
        totalCost: 150,
        profit: 250,
        profitPercent: 166.67,
        status: "completed",
        progress: 100,
        completedQuantity: 500,
        jobId: "job-8",
        startedAt: "2024-12-27T08:00:00Z",
        completedAt: "2024-12-27T16:00:00Z",
      },
    ],
    subtotal: 400,
    discount: 20,
    total: 380,
    totalCost: 150,
    totalProfit: 230,
    paymentStatus: "paid",
    paymentProof: "/proofs/slip-003.jpg",
    paidAt: "2024-12-27T07:55:00Z",
    status: "completed",
    progress: 100,
    trackingUrl: "seller.meelike.com/track/ORD-2025-001",
    createdAt: "2024-12-27T07:50:00Z",
    updatedAt: "2024-12-27T16:00:00Z",
    confirmedAt: "2024-12-27T07:55:00Z",
    completedAt: "2024-12-27T16:00:00Z",
  },

  // ===== CANCELLED (ยกเลิก) =====
  {
    id: "order-cancelled-1",
    orderNumber: "ORD-2024-999",
    sellerId: "seller-1",
    customer: {
      name: "คุณเอ",
      contactType: "line",
      contactValue: "@customer_a",
      note: "ขอยกเลิกเพราะใส่ URL ผิดค่ะ",
    },
    items: [
      {
        id: "item-cancel-1",
        orderId: "order-cancelled-1",
        serviceId: "svc-1",
        serviceName: "ไลค์ Facebook (Bot)",
        serviceType: "bot",
        platform: "facebook",
        type: "like",
        targetUrl: "https://facebook.com/wrong_url",
        quantity: 500,
        unitPrice: 0.15,
        subtotal: 75,
        costPerUnit: 0.08,
        totalCost: 40,
        profit: 35,
        profitPercent: 87.5,
        status: "cancelled",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 75,
    discount: 0,
    total: 75,
    totalCost: 40,
    totalProfit: 35,
    paymentStatus: "refunded",
    status: "cancelled",
    progress: 0,
    trackingUrl: "seller.meelike.com/track/ORD-2024-999",
    cancelReason: "ลูกค้าขอยกเลิก - ใส่ URL ผิด",
    createdAt: "2024-12-25T15:30:00Z",
    updatedAt: "2024-12-25T16:00:00Z",
    cancelledAt: "2024-12-25T16:00:00Z",
  },
  {
    id: "order-cancelled-2",
    orderNumber: "ORD-2024-998",
    sellerId: "seller-1",
    customer: {
      name: "ร้านขายเสื้อผ้า",
      contactType: "facebook",
      contactValue: "fb.com/clotheshop",
    },
    items: [
      {
        id: "item-cancel-2",
        orderId: "order-cancelled-2",
        serviceId: "svc-4",
        serviceName: "Follow Instagram (Bot)",
        serviceType: "bot",
        platform: "instagram",
        type: "follow",
        targetUrl: "https://instagram.com/clotheshop",
        quantity: 2000,
        unitPrice: 0.2,
        subtotal: 400,
        costPerUnit: 0.1,
        totalCost: 200,
        profit: 200,
        profitPercent: 100,
        status: "cancelled",
        progress: 0,
        completedQuantity: 0,
      },
    ],
    subtotal: 400,
    discount: 0,
    total: 400,
    totalCost: 200,
    totalProfit: 200,
    paymentStatus: "pending",
    status: "cancelled",
    progress: 0,
    trackingUrl: "seller.meelike.com/track/ORD-2024-998",
    cancelReason: "ไม่ชำระเงินภายในเวลาที่กำหนด",
    createdAt: "2024-12-24T11:00:00Z",
    updatedAt: "2024-12-24T23:00:00Z",
    cancelledAt: "2024-12-24T23:00:00Z",
  },
];

// ===== SELLER STATS =====
export const mockSellerStats = {
  todayRevenue: 1250,
  monthRevenue: 28500,
  todayOrders: 12,
  monthOrders: 245,
  activeTeamMembers: 38,
  pendingReviews: 5,
  pendingPayouts: 2450,
};
