import type { Team, TeamMember, JobClaim, TeamJob, TeamPayout, TeamReview } from "@/types";
import { mockWorkers } from "./worker";

// ===== MOCK TEAMS (Seller มีได้หลายทีม) =====
export const mockTeams: Team[] = [
  {
    id: "team-1",
    sellerId: "seller-1",
    name: "JohnBoost Team",
    description: "ทีมงานคุณภาพ รับงาน Social Media ทุกประเภท",
    rules: [
      "แคปหลักฐานทุกงาน",
      "ส่งงานตรงเวลา",
      "ไม่จองงานถ้าทำไม่ไหว",
      "สอบถามก่อนได้เสมอ",
    ],
    inviteCode: "JOHN-2024-ABC",
    requireApproval: true,
    isPublic: true,
    isRecruiting: true,
    recruitingMessage: "รับน้องใหม่ทุกวัน! จ่ายไวทุก 2 วัน",
    memberCount: 45,
    activeJobCount: 3,
    totalJobsCompleted: 1250,
    rating: 4.8,
    ratingCount: 156,
    status: "active",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "team-2",
    sellerId: "seller-1",
    name: "JohnBoost TikTok",
    description: "ทีมเฉพาะทาง TikTok งานเยอะ จ่ายไว",
    rules: [
      "ต้องมีบัญชี TikTok ที่ผ่านการยืนยัน",
      "แคปหลักฐานทุกงาน",
      "ส่งงานภายใน 6 ชม.",
    ],
    inviteCode: "JOHN-TIKTOK-XYZ",
    requireApproval: true,
    isPublic: true,
    isRecruiting: true,
    recruitingMessage: "รับเฉพาะคนที่มี TikTok! งานเยอะมาก",
    memberCount: 28,
    activeJobCount: 5,
    totalJobsCompleted: 890,
    rating: 4.7,
    ratingCount: 98,
    status: "active",
    isActive: true,
    createdAt: "2024-03-15",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "team-3",
    sellerId: "seller-1",
    name: "JohnBoost Premium",
    description: "ทีม VIP สำหรับงานพิเศษ ราคาสูง คุณภาพเยี่ยม",
    rules: [
      "ต้องเป็น Gold Level ขึ้นไป",
      "Rating 4.5+",
      "งานด่วนต้องส่งภายใน 2 ชม.",
      "คุณภาพต้องสมบูรณ์แบบ",
    ],
    inviteCode: "JOHN-VIP-2024",
    requireApproval: true,
    isPublic: false, // ไม่แสดงในตลาดกลาง
    isRecruiting: false, // เชิญเท่านั้น
    recruitingMessage: "",
    memberCount: 12,
    activeJobCount: 2,
    totalJobsCompleted: 320,
    rating: 4.95,
    ratingCount: 45,
    status: "active",
    isActive: true,
    createdAt: "2024-06-01",
    updatedAt: new Date().toISOString(),
  },
];

// Legacy: เข้ากันได้กับ code เดิม
export const mockTeam: Team = mockTeams[0];

// ===== MOCK TEAM MEMBERS =====
export const mockTeamMembers: TeamMember[] = [
  // Team 1 members
  {
    id: "tm-1",
    teamId: "team-1",
    workerId: "worker-1",
    status: "active",
    role: "worker",
    permissions: [],
    jobsCompleted: 180,
    totalEarned: 9500,
    rating: 4.9,
    ratingCount: 175,
    joinedAt: "2024-01-20",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "tm-2",
    teamId: "team-1",
    workerId: "worker-2",
    status: "active",
    role: "assistant",
    permissions: ["dashboard:view", "members:view", "members:invite", "jobs:view", "jobs:create", "jobs:review"],
    jobsCompleted: 95,
    totalEarned: 4800,
    rating: 4.7,
    ratingCount: 92,
    joinedAt: "2024-03-01",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "tm-3",
    teamId: "team-1",
    workerId: "worker-3",
    status: "inactive",
    role: "worker",
    permissions: [],
    jobsCompleted: 35,
    totalEarned: 1400,
    rating: 4.5,
    ratingCount: 33,
    joinedAt: "2024-06-15",
    lastActiveAt: "2024-12-20",
  },
  // Team 2 members
  {
    id: "tm-4",
    teamId: "team-2",
    workerId: "worker-1",
    status: "active",
    role: "worker",
    permissions: [],
    jobsCompleted: 45,
    totalEarned: 2800,
    rating: 4.8,
    ratingCount: 42,
    joinedAt: "2024-04-01",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "tm-5",
    teamId: "team-2",
    workerId: "worker-2",
    status: "active",
    role: "worker",
    permissions: [],
    jobsCompleted: 62,
    totalEarned: 3100,
    rating: 4.6,
    ratingCount: 58,
    joinedAt: "2024-04-15",
    lastActiveAt: new Date().toISOString(),
  },
  // Team 3 (VIP) members
  {
    id: "tm-6",
    teamId: "team-3",
    workerId: "worker-1",
    status: "active",
    role: "worker",
    permissions: [],
    jobsCompleted: 85,
    totalEarned: 6500,
    rating: 4.95,
    ratingCount: 82,
    joinedAt: "2024-06-15",
    lastActiveAt: new Date().toISOString(),
  },
];

// ===== MOCK TEAM JOBS =====
export const mockTeamJobs: TeamJob[] = [
  {
    id: "job-1",
    teamId: "team-1",
    orderId: "order-1",
    orderNumber: "ORD-2024-001",
    serviceName: "เม้น Facebook (คนไทยจริง)",
    platform: "facebook",
    quantity: 50,
    completedQuantity: 32,
    pricePerUnit: 0.5,
    totalPayout: 25,
    targetUrl: "https://facebook.com/post/xxx",
    instructions: "กรุณาแสดงความคิดเห็นเป็นภาษาไทยที่เป็นธรรมชาติ ไม่ซ้ำกัน อย่างน้อย 10 คำ ห้ามใช้ Emoji มากเกินไป แคปหลักฐานทุกครั้ง",
    status: "in_progress",
    assignedWorker: mockWorkers[0],
    deadline: new Date(Date.now() + 3600000 * 4).toISOString(),
    createdAt: "2024-12-30T08:00:00Z",
  },
  {
    id: "job-2",
    teamId: "team-1",
    orderId: "order-1",
    orderNumber: "ORD-2024-001",
    serviceName: "Follow Instagram (คนไทยจริง)",
    platform: "instagram",
    quantity: 200,
    completedQuantity: 0,
    pricePerUnit: 0.3,
    totalPayout: 60,
    targetUrl: "https://instagram.com/somchai_shop",
    instructions: "กดติดตามบัญชีนี้ ต้องใช้บัญชีจริง มีรูปโปรไฟล์ มีโพสต์อย่างน้อย 5 โพสต์ อย่ากดเลิกติดตามภายใน 7 วัน แคปหลักฐานส่ง",
    status: "pending",
    deadline: new Date(Date.now() + 3600000 * 24).toISOString(),
    createdAt: "2024-12-30T08:30:00Z",
  },
  {
    id: "job-3",
    teamId: "team-1",
    orderId: "order-3",
    orderNumber: "ORD-2024-003",
    serviceName: "ไลค์ Facebook (คนไทยจริง)",
    platform: "facebook",
    quantity: 100,
    completedQuantity: 100,
    pricePerUnit: 0.2,
    totalPayout: 20,
    targetUrl: "https://facebook.com/post/yyy",
    instructions: "กดไลค์โพสต์นี้ ใช้บัญชีคนไทยจริง มีรูปโปรไฟล์ มีเพื่อน 100+ แคปหลักฐานทุกครั้ง",
    status: "pending_review",
    assignedWorker: mockWorkers[1],
    submittedAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: "2024-12-29T10:00:00Z",
  },
  {
    id: "job-4",
    teamId: "team-2",
    orderId: "order-4",
    orderNumber: "ORD-2024-004",
    serviceName: "View TikTok (คนไทยจริง)",
    platform: "tiktok",
    quantity: 500,
    completedQuantity: 500,
    pricePerUnit: 0.1,
    totalPayout: 50,
    targetUrl: "https://tiktok.com/@shop/video/xxx",
    instructions: "เปิดวิดีโอนี้ดูให้จบ อย่างน้อย 10 วินาที ใช้บัญชี TikTok ที่ยืนยันแล้ว แคปหลักฐานส่ง",
    status: "completed",
    assignedWorker: mockWorkers[0],
    completedAt: "2024-12-28T15:00:00Z",
    createdAt: "2024-12-28T10:00:00Z",
  },
  {
    id: "job-5",
    teamId: "team-1",
    orderId: "order-5",
    orderNumber: "ORD-2024-005",
    serviceName: "ไลค์ Facebook (คนไทยจริง)",
    platform: "facebook",
    quantity: 50,
    completedQuantity: 50,
    pricePerUnit: 0.2,
    totalPayout: 10,
    targetUrl: "https://facebook.com/post/zzz",
    status: "pending_review",
    assignedWorker: mockWorkers[2],
    submittedAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: "2024-12-27T14:00:00Z",
  },
];

// ===== MOCK TEAM PAYOUTS =====
export const mockTeamPayouts: TeamPayout[] = [
  {
    id: "payout-1",
    workerId: "worker-1",
    worker: mockWorkers[0],
    amount: 250,
    jobCount: 15,
    status: "pending",
    requestedAt: new Date(Date.now() - 86400000).toISOString(),
    paymentMethod: "promptpay",
    paymentAccount: "0811111111",
  },
  {
    id: "payout-2",
    workerId: "worker-2",
    worker: mockWorkers[1],
    amount: 180,
    jobCount: 12,
    status: "pending",
    requestedAt: new Date(Date.now() - 172800000).toISOString(),
    paymentMethod: "bank",
    bankName: "กรุงไทย",
    paymentAccount: "987-6-54321-0",
    accountName: "นางสาว มิ้นท์ สดใส",
  },
  {
    id: "payout-3",
    workerId: "worker-1",
    worker: mockWorkers[0],
    amount: 450,
    jobCount: 28,
    status: "completed",
    requestedAt: new Date(Date.now() - 604800000).toISOString(),
    completedAt: new Date(Date.now() - 518400000).toISOString(),
    paymentMethod: "promptpay",
    paymentAccount: "0811111111",
    transactionRef: "TXN-20241223-001",
  },
  {
    id: "payout-4",
    workerId: "worker-2",
    worker: mockWorkers[1],
    amount: 320,
    jobCount: 20,
    status: "completed",
    requestedAt: new Date(Date.now() - 1209600000).toISOString(),
    completedAt: new Date(Date.now() - 1123200000).toISOString(),
    paymentMethod: "bank",
    bankName: "กรุงไทย",
    paymentAccount: "987-6-54321-0",
    accountName: "นางสาว มิ้นท์ สดใส",
    transactionRef: "TXN-20241216-002",
  },
  {
    id: "payout-5",
    workerId: "worker-3",
    worker: mockWorkers[2],
    amount: 95,
    jobCount: 8,
    status: "completed",
    requestedAt: new Date(Date.now() - 1814400000).toISOString(),
    completedAt: new Date(Date.now() - 1728000000).toISOString(),
    paymentMethod: "promptpay",
    paymentAccount: "0833333333",
    transactionRef: "TXN-20241209-003",
  },
];

// ===== MOCK JOB CLAIMS =====
export const mockJobClaims: JobClaim[] = [
  {
    id: "claim-1",
    jobId: "job-1",
    workerId: "worker-1",
    workerAccountId: "wa-1",
    quantity: 30,
    earnAmount: 6,
    status: "submitted",
    submittedAt: new Date().toISOString(),
    proofUrls: ["/proofs/claim-1-1.jpg", "/proofs/claim-1-2.jpg"],
    actualQuantity: 30,
    createdAt: "2024-12-30T08:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "claim-2",
    jobId: "job-1",
    workerId: "worker-2",
    workerAccountId: "wa-2",
    quantity: 50,
    earnAmount: 10,
    status: "submitted",
    submittedAt: new Date().toISOString(),
    proofUrls: ["/proofs/claim-2-1.jpg", "/proofs/claim-2-2.jpg", "/proofs/claim-2-3.jpg"],
    actualQuantity: 50,
    createdAt: "2024-12-30T08:15:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "claim-3",
    jobId: "job-1",
    workerId: "worker-1",
    workerAccountId: "wa-1",
    quantity: 20,
    earnAmount: 4,
    status: "approved",
    submittedAt: "2024-12-30T09:00:00Z",
    proofUrls: ["/proofs/claim-3-1.jpg"],
    actualQuantity: 20,
    reviewedAt: "2024-12-30T09:30:00Z",
    reviewedBy: "seller-1",
    sellerRating: 5,
    // Worker รีวิว Team แล้ว
    workerTeamRating: 5,
    workerTeamReview: "แม่ทีมใจดีมาก จ่ายไวทุกครั้ง มีงานให้ทำตลอด",
    workerTeamReviewTags: ["pays_fast", "pays_fair", "consistent_work"],
    createdAt: "2024-12-30T08:30:00Z",
    updatedAt: "2024-12-30T09:30:00Z",
  },
];

// ===== MOCK TEAM REVIEWS =====
export const mockTeamReviews: TeamReview[] = [
  {
    id: "review-1",
    teamId: "team-1",
    workerId: "worker-1",
    worker: mockWorkers[0],
    jobClaimId: "claim-3",
    rating: 5,
    review: "แม่ทีมใจดีมาก จ่ายไวทุกครั้ง มีงานให้ทำตลอด",
    tags: ["pays_fast", "pays_fair", "consistent_work"],
    isAnonymous: false,
    createdAt: "2024-12-30T10:00:00Z",
  },
  {
    id: "review-2",
    teamId: "team-1",
    workerId: "worker-2",
    worker: mockWorkers[1],
    rating: 5,
    review: "ติดต่อง่าย อธิบายงานชัดเจน แนะนำเลย!",
    tags: ["good_communication", "clear_instructions", "friendly"],
    isAnonymous: false,
    createdAt: "2024-12-28T14:00:00Z",
  },
  {
    id: "review-3",
    teamId: "team-1",
    workerId: "worker-3",
    worker: mockWorkers[2],
    rating: 4,
    review: "งานเยอะ จ่ายตรงเวลา แต่บางทีตอบช้าหน่อย",
    tags: ["consistent_work", "pays_fast"],
    isAnonymous: true,
    createdAt: "2024-12-25T09:00:00Z",
  },
  {
    id: "review-4",
    teamId: "team-1",
    workerId: "worker-1",
    worker: mockWorkers[0],
    rating: 5,
    review: "ทีมที่ดีที่สุดที่เคยเจอ",
    tags: ["pays_fast", "pays_fair", "friendly", "consistent_work"],
    isAnonymous: false,
    createdAt: "2024-12-20T16:00:00Z",
  },
];
