import type { Worker, WorkerAccount, WorkerJob } from "@/types";

// ===== MOCK WORKERS =====
export const mockWorkers: Worker[] = [
  {
    id: "worker-1",
    userId: "user-w1",
    displayName: "นุ่น",
    avatar: "/avatars/worker-1.jpg",
    bio: "ขยันทำงานค่ะ",
    lineId: "@nuna",
    phone: "081-111-1111",
    bankName: "กสิกร",
    bankAccount: "123-4-56789-0",
    bankAccountName: "นางสาว นุ่น ใจดี",
    promptPayId: "0811111111",
    totalJobs: 256,
    totalEarned: 12500,
    completionRate: 98.5,
    rating: 4.9,
    ratingCount: 245,
    level: "gold",
    totalJobsCompleted: 245,
    pendingBalance: 15,
    availableBalance: 127.5,
    isActive: true,
    isBanned: false,
    teamIds: ["team-1", "team-2"],
    createdAt: "2024-01-15",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "worker-2",
    userId: "user-w2",
    displayName: "มิ้นท์",
    avatar: "/avatars/worker-2.jpg",
    bio: "รับงานทุกประเภท",
    lineId: "@mint",
    phone: "082-222-2222",
    bankName: "กรุงไทย",
    bankAccount: "987-6-54321-0",
    bankAccountName: "นางสาว มิ้นท์ สดใส",
    promptPayId: "0822222222",
    totalJobs: 134,
    totalEarned: 6800,
    completionRate: 96.2,
    rating: 4.7,
    ratingCount: 128,
    level: "silver",
    totalJobsCompleted: 128,
    pendingBalance: 25,
    availableBalance: 85.5,
    isActive: true,
    isBanned: false,
    teamIds: ["team-1"],
    createdAt: "2024-02-20",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "worker-3",
    userId: "user-w3",
    displayName: "เบส",
    avatar: "/avatars/worker-3.jpg",
    lineId: "@bass",
    phone: "083-333-3333",
    totalJobs: 52,
    totalEarned: 2100,
    completionRate: 92.5,
    rating: 4.5,
    ratingCount: 45,
    level: "bronze",
    totalJobsCompleted: 45,
    pendingBalance: 0,
    availableBalance: 42,
    isActive: false,
    isBanned: false,
    teamIds: ["team-1"],
    createdAt: "2024-06-10",
    lastActiveAt: "2024-12-20",
  },
];

// ===== MOCK WORKER ACCOUNTS =====
export const mockWorkerAccounts: WorkerAccount[] = [
  {
    id: "wa-1",
    workerId: "worker-1",
    platform: "facebook",
    username: "nuna.jaidee",
    profileUrl: "https://facebook.com/nuna.jaidee",
    screenshotUrl: "/screenshots/wa-1.jpg",
    verificationStatus: "verified",
    verifiedAt: "2024-01-20",
    verifiedBy: "ai",
    aiResult: {
      passed: true,
      confidence: 0.95,
      hasProfilePicture: true,
      detectedFollowers: 850,
      usernameMatch: true,
      notes: "Account verified successfully",
    },
    followers: 850,
    profilePictureExists: true,
    accountAge: "3 years",
    isActive: true,
    lastUsedAt: new Date().toISOString(),
    jobsCompleted: 180,
    createdAt: "2024-01-20",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wa-2",
    workerId: "worker-2",
    platform: "facebook",
    username: "mint.sodsai",
    profileUrl: "https://facebook.com/mint.sodsai",
    screenshotUrl: "/screenshots/wa-2.jpg",
    verificationStatus: "verified",
    verifiedAt: "2024-03-05",
    verifiedBy: "ai",
    aiResult: {
      passed: true,
      confidence: 0.92,
      hasProfilePicture: true,
      detectedFollowers: 620,
      usernameMatch: true,
      notes: "Account verified successfully",
    },
    followers: 620,
    profilePictureExists: true,
    accountAge: "2 years",
    isActive: true,
    lastUsedAt: new Date().toISOString(),
    jobsCompleted: 95,
    createdAt: "2024-03-05",
    updatedAt: new Date().toISOString(),
  },
];

// ===== WORKER STATS =====
export const mockWorkerStats = {
  availableBalance: 127.5,
  pendingBalance: 15,
  totalEarned: 2450,
  todayEarned: 24,
  weeklyRank: 1,
  streak: 7,
};

// ===== WORKER JOBS =====
export const mockWorkerJobs: {
  in_progress: WorkerJob[];
  pending_review: WorkerJob[];
  completed: WorkerJob[];
} = {
  in_progress: [
    {
      id: "job-1",
      teamName: "JohnBoost Team",
      serviceName: "ไลค์ Facebook",
      platform: "facebook",
      type: "human",
      targetUrl: "https://facebook.com/post/123",
      quantity: 100,
      completedQuantity: 65,
      pricePerUnit: 0.2,
      deadline: new Date(Date.now() + 3600000 * 2).toISOString(),
      status: "in_progress",
    },
    {
      id: "job-2",
      teamName: "SocialPro Team",
      serviceName: "Follow Instagram",
      platform: "instagram",
      type: "human",
      targetUrl: "https://instagram.com/user123",
      quantity: 50,
      completedQuantity: 20,
      pricePerUnit: 0.3,
      deadline: new Date(Date.now() + 3600000 * 5).toISOString(),
      status: "in_progress",
    },
  ],
  pending_review: [
    {
      id: "job-3",
      teamName: "JohnBoost Team",
      serviceName: "เม้น Facebook",
      platform: "facebook",
      type: "human",
      targetUrl: "https://facebook.com/post/456",
      quantity: 30,
      completedQuantity: 30,
      pricePerUnit: 1.5,
      submittedAt: new Date(Date.now() - 3600000).toISOString(),
      status: "pending_review",
    },
    {
      id: "job-4",
      teamName: "BoostKing Team",
      serviceName: "ไลค์ Facebook",
      platform: "facebook",
      type: "human",
      targetUrl: "https://facebook.com/post/789",
      quantity: 50,
      completedQuantity: 50,
      pricePerUnit: 0.2,
      submittedAt: new Date(Date.now() - 7200000).toISOString(),
      status: "pending_review",
    },
    {
      id: "job-5",
      teamName: "SocialPro Team",
      serviceName: "View TikTok",
      platform: "tiktok",
      type: "human",
      targetUrl: "https://tiktok.com/@user/video/123",
      quantity: 200,
      completedQuantity: 200,
      pricePerUnit: 0.08,
      submittedAt: new Date(Date.now() - 10800000).toISOString(),
      status: "pending_review",
    },
  ],
  completed: [
    {
      id: "job-6",
      teamName: "JohnBoost Team",
      serviceName: "ไลค์ Facebook",
      platform: "facebook",
      type: "human",
      targetUrl: "https://facebook.com/post/111",
      quantity: 100,
      completedQuantity: 100,
      pricePerUnit: 0.2,
      completedAt: new Date(Date.now() - 86400000).toISOString(),
      earnings: 20,
      status: "completed",
    },
    {
      id: "job-7",
      teamName: "SocialPro Team",
      serviceName: "Follow Instagram",
      platform: "instagram",
      type: "human",
      targetUrl: "https://instagram.com/user456",
      quantity: 80,
      completedQuantity: 80,
      pricePerUnit: 0.3,
      completedAt: new Date(Date.now() - 172800000).toISOString(),
      earnings: 24,
      status: "completed",
    },
  ],
};

// Active jobs for worker dashboard
export const mockActiveJobs = [
  {
    id: "job-1",
    title: "ไลค์ Facebook แฟนเพจ",
    team: "JohnBoost Team",
    deadline: "2 ชม.",
    payout: 20,
    progress: 65,
    total: 100,
  },
  {
    id: "job-2",
    title: "Follow Instagram",
    team: "SocialPro",
    deadline: "5 ชม.",
    payout: 15,
    progress: 20,
    total: 50,
  },
];
